export const errorMessage = {
  emailFormat: 'Please enter the correct email address',
  passwordFormat:
    'Password should be atleast 6 characters including one uppercase letter, one special character and alphanumeric characters',
  passwordEmpty: 'Please enter password',
  emailEmpty: 'Please enter email',
  addressEmpty: 'Please enter address',
  cityEmpty: 'Please enter city',
  descriptionEmpty: 'Please enter description',
  projectOwnerEmpty: 'Please select projectOwner',
  startDateEmpty: 'Please select startDate',
  priorityEmpty: 'Please select priority',
  endDateEmpty: 'Please select endDate',
  countryEmpty: 'Please enter country',
  stateEmpty: 'Please enter state',
  pincodeEmpty: 'Please enter pincode',
  phoneEmpty: 'Please enter phone number',
  firstNameEmpty: 'Please enter first name',
  lastNameEmpty: 'Please enter last name',
  passwordMatch: 'Confirm password is not same as password.',
  confirmPasswordEmpty: 'Please enter the confirm password',
  nameEmpty: 'Name can not be empty',
  fetchingRole: 'There is an error is fetching roles. Please try again.',
  fetchingGroupUsers: 'There is an error is fetching group users. Please try again.',
  invalidCredentials: 'Email or password is not correct. Please try again.',
  userAlreadyExists: 'Email already registered. Please try with different email address.',
  technicalIssue: 'Technical issue. Please try to contact Admin support.',
  sessionExpired: 'Your session has been expired please login again',
  networkError: 'Network Error. Please try again',
  roleEmpty: 'Please select Role.',
  nameEror: 'Please enter only alphabetical characters.',
  fileSize: 'File size exceeds the max file upload size.',
  fileFormat: 'This type of file is not supported',
  fileLimit: 'Please upload only one file.',
  emailAlreadyInChips: 'Name or email already entered. Please check and try again.',
  userNotRegistered: 'User is not registered. Please verify again',
  titleIsRequired: 'Please enter the title of meeting',
  authorised: 'You do not have persmissions to perfom this operation',
  nameOrEmailRequired: 'Please enter a valid name or email',
  fileNameLimit: 'File name is too long, please rename the file and try again.',
  addMember: 'Please either select the member from the list or enter the valid email',
  checkBox: 'Please accept terms and condition',
  groupDescription: 'Tell us more about your Group',
  groupDescriptionEmpty: 'Please specify something',
  formName: 'Required forn name',
}
